services:
  auth:
    build: .
    container_name: psitest-auth
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8002:80
    networks:
      - psitest
    env_file: ".env"
networks:
  psitest:
    external: true
