services:
  auth:
    build: .
    container_name: psitest-auth
    command: fastapi dev app --host 0.0.0.0 --port 80
    ports:
      - 8002:80
    volumes:
      - .:/app
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true